// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class HomeTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void home() {
    // Test name: Home
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://www.demoblaze.com/");
    // 2 | setWindowSize | 1382x744 | 
    driver.manage().window().setSize(new Dimension(1382, 744));
    // 3 | click | css=.active > .nav-link | 
    driver.findElement(By.cssSelector(".active > .nav-link")).click();
    // 4 | click | css=.active > .nav-link | 
    driver.findElement(By.cssSelector(".active > .nav-link")).click();
    // 5 | click | linkText=Samsung galaxy s6 | 
    driver.findElement(By.linkText("Samsung galaxy s6")).click();
    // 6 | click | css=.active > .nav-link | 
    driver.findElement(By.cssSelector(".active > .nav-link")).click();
    // 7 | click | css=.col-lg-4:nth-child(6) .card-img-top | 
    driver.findElement(By.cssSelector(".col-lg-4:nth-child(6) .card-img-top")).click();
    // 8 | click | css=.active > .nav-link | 
    driver.findElement(By.cssSelector(".active > .nav-link")).click();
  }
}
