// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class LoginNotFillPasswordTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void loginNotFillPassword() {
    driver.Navigate().GoToUrl("https://www.demoblaze.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(1382, 744);
    driver.FindElement(By.Id("login2")).Click();
    driver.FindElement(By.Id("loginusername")).Click();
    driver.FindElement(By.Id("loginusername")).SendKeys("ricky123456");
    driver.FindElement(By.CssSelector("#logInModal .btn-primary")).Click();
    Assert.That(driver.SwitchTo().Alert().Text, Is.EqualTo("Please fill out Username and Password."));
    driver.FindElement(By.CssSelector("#logInModal .btn-secondary")).Click();
  }
}
