// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class LoginSuccsesTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void loginSuccses() {
    driver.Navigate().GoToUrl("https://www.demoblaze.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(1382, 744);
    driver.FindElement(By.Id("login2")).Click();
    driver.FindElement(By.Id("loginusername")).Click();
    driver.FindElement(By.Id("loginusername")).SendKeys("ricky123456");
    driver.FindElement(By.Id("loginpassword")).Click();
    driver.FindElement(By.Id("loginpassword")).SendKeys("ricky123456");
    driver.FindElement(By.CssSelector("#logInModal .btn-primary")).Click();
    driver.FindElement(By.Id("nameofuser")).Click();
  }
}
