// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class RegisterSuccsesTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void registerSuccses() {
    driver.Navigate().GoToUrl("https://www.demoblaze.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(1382, 744);
    driver.FindElement(By.Id("signin2")).Click();
    driver.FindElement(By.Id("sign-username")).Click();
    driver.FindElement(By.Id("sign-username")).SendKeys("rickymaulana12345");
    driver.FindElement(By.Id("sign-password")).Click();
    driver.FindElement(By.Id("sign-password")).SendKeys("rickymaulana1234567");
    driver.FindElement(By.CssSelector("#signInModal .btn-primary")).Click();
  }
}
