// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class RegisterNotFillUsernameTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void registerNotFillUsername() {
    // Test name: Register_Not_Fill_Username
    // Step # | name | target | value
    // 1 | open | / | 
    driver.Navigate().GoToUrl("https://www.demoblaze.com/");
    // 2 | setWindowSize | 1382x744 | 
    driver.Manage().Window.Size = new System.Drawing.Size(1382, 744);
    // 3 | click | id=signin2 | 
    driver.FindElement(By.Id("signin2")).Click();
    // 4 | click | id=sign-password | 
    driver.FindElement(By.Id("sign-password")).Click();
    // 5 | type | id=sign-password | maulana123456
    driver.FindElement(By.Id("sign-password")).SendKeys("maulana123456");
    // 6 | click | css=#signInModal .btn-primary | 
    driver.FindElement(By.CssSelector("#signInModal .btn-primary")).Click();
    // 7 | assertAlert | Please fill out Username and Password. | 
    Assert.That(driver.SwitchTo().Alert().Text, Is.EqualTo("Please fill out Username and Password."));
    // 8 | click | css=#signInModal .btn-secondary | 
    driver.FindElement(By.CssSelector("#signInModal .btn-secondary")).Click();
  }
}
